# https://taskfile.dev

version: '3'

vars:
  VERSION: 0.0.3

tasks:
  up:
    cmds:
      - docker compose up -d

  down:
    cmds:
      - docker compose down --rmi local

  docker-build:
    cmds:
      - docker build . -t thomasnewman/thom-auth:{{.VERSION}}

  docker-deploy:
    cmds:
      - task: docker-build
      - docker push thomasnewman/thom-auth:{{.VERSION}}
      - docker rmi thomasnewman/thom-auth:{{.VERSION}}
